# Generated by Django 3.2.5 on 2021-07-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=120)),
                ('job_description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
